version: '2.3'

networks:  
  graylog:

volumes:  
  graylog_data:  

services:  
  mongodb:  
    image: mongo:3
    container_name: graylog-mongodb
    restart: always  
    volumes:  
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    networks:   
      - graylog

  elasticsearch:
    image: elasticsearch:2
    container_name: graylog-elasticsearch
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    command:
      - elasticsearch
      - -Des.cluster.name="graylog"

  graylog:
    image: graylog2/server
    container_name: graylog
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    links:
      - mongodb
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201/udp"
    environment:
      - GRAYLOG_WEB_ENDPOINT_URI="http://192.168.3.25:9000/api"
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918