version: '3'

services:
  
  gelf-log_pusher-a:
    image: busybox:1.29.2
    command: sh -c 'while true;do echo "This is a log from log_pusher-a";sleep 5;done'
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: log_pusher-a

  gelf-log_pusher-b:
    image: busybox:1.29.2
    command: sh -c 'while true;do echo "This is a log from log_pusher-b";sleep 1;done'
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: log_pusher-b

  # fluentd-log_pusher-a:
  #   image: busybox:1.29.2
  #   command: sh -c 'while true;do echo "This is a log from log_pusher-b";sleep 5;done'
  #   logging:
  #     driver: fluentd
  #     options:
  #       fluentd-address: localhost:24224
  #       tag: log_pusher-a

  # fluentd-log_pusher-b:
  #   image: busybox:1.29.2
  #   command: sh -c 'while true;do echo "This is a log from log_pusher-b";sleep 1;done'
  #   logging:
  #     driver: fluentd
  #     options:
  #       fluentd-address: localhost:24224
  #       tag: log_pusher-b