# docker swarm mode

version: '3.4'
services:

  registry:
    image: registry:2.6.2
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.gpu != nvidia

volumes:
  
  registry_data:
    driver: local