version: '3.7'

services:

  http-disk:
    image: nginx:1.15-alpine
    ports:
      - '80:80'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/conf.d:/etc/nginx/conf.d:ro
      - /mnt/data/FTP_DATA:/mnt/data/FTP_DATA:ro
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    restart: always