version: '3'

volumes: 
  nextcloud_data:
  db_data:

services: 

  cloud_disk:
    image: nextcloud:15.0.0-apache
    container_name: nextcloud
    ports: 
      - 80:80
    volumes: 
      - nextcloud_data:/var/www/html
    restart: always

  db:
    image: mariadb # 2018年12月24日 10.3.11
    environment: 
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    