version: '3'
services:

  cadvisor:
    image: google/cadvisor:v0.30.2
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw 
      - /sys:/sys:ro 
      - /var/lib/docker:/var/lib/docker:ro 
      - /dev/disk:/dev/disk:ro
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    ports:
      - 8080:8080 
    restart: always
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m


