version: '3.7'

services:

  jenkins:
    container_name: jenkins
    image: jenkins:2.60.3
    network_mode: bridge
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      - jenkins_data:/var/jenkins_home
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: '10m'
    restart: always

volumes:

  jenkins_data:
