# stack.yml for Beats Elasticsearch Kibana

version: '3.4'

services:

  kibana:
    # build:
    #   context: build/kibana
    image: registry.cn-hangzhou.aliyuncs.com/xiangxiaoc/kibana:5.6.11
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    restart: always

  elasticsearch:
    image: elasticsearch:5.6.11
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./config/elasticsearch:/usr/share/elasticsearch/config
    restart: always

  logstash:
    image: logstash:5.6.11
    restart: always

volumes:
  elasticsearch_data:
    driver: local
    