version: '3'
services:

  portainer:
    image: portainer/portainer:1.17.1
    ports:
      - 9000:9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    restart: always
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m

volumes:
  portainer_data: 
    driver: local
