version: '3'

services:

  agent:
    image: portainer/agent:1.0.0
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - agent_network
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    deploy:
      mode: global

  portainer:
    image: portainer/portainer:1.19.1
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - portainer_data:/data
    networks:
      - agent_network
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  agent_network:
    driver: overlay

volumes:
  portainer_data:
