version: '3'
services:

  # 如果宿主机上有MySQL的话建议直接使用
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/mysql:/var/lib/mysql # 数据持久化
    stop_grace_period: 1m
    command: --character-set-server=utf8 --collation-server=utf8_bin
    restart: always
  
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-4.0.1
    # image: zabbix/zabbix-server-mysql:ubuntu-4.0.1
    # image: zabbix/zabbix-server-mysql:centos-4.0.1
    ports:
      - '10051:10051'
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=root
      - ZBX_JAVAGATEWAY=zabbix-java-gateway
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/zabbix-server/zabbix_server.conf:/etc/zabbix/zabbix_server.conf # 自定义配置
      - /usr/lib/zabbix/alertscripts
    restart: always    

  # zabbix-java-gateway:
  #   image: zabbix/zabbix-java-gateway:alpine-4.0.1
  #   # image: zabbix/zabbix-java-gateway:ubuntu-4.0.1
  #   # image: zabbix/zabbix-java-gateway:centos-4.0.1
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /etc/timezone:/etc/timezone:ro
  #   restart: always

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:alpine-4.0.1
    # image: zabbix/zabbix-web-nginx-mysql:ubuntu-4.0.1
    # image: zabbix/zabbix-web-nginx-mysql:centos-4.0.1
    ports:
      - '8050:80'
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=root
      - PHP_TZ=Asia/Shanghai # 定制时区
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/zabbix-web-nginx-mysql/include/defines.inc.php:/usr/share/zabbix/include/defines.inc.php # 自定义字体
      - ./config/zabbix-web-nginx-mysql/fonts/msyh.ttf:/usr/share/zabbix/fonts/msyh.ttf # 提供字体
    restart: always

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-4.0.1
    # image: zabbix/zabbix-agent:ubuntu-4.0.1
    # image: zabbix/zabbix-agent:centos-4.0.1
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/zabbix-agent/zabbix_agentd.conf:/etc/zabbix/zabbix_agentd.conf
    restart: always